import React,{useState,useMemo,useEffect,useRef} from 'react';
import{createRoot}from'react-dom/client';
import{SeaMap,type Camera,type Layers}from'./Map';
import{events}from'./data/events';
import{sources}from'./data/sources';
import{units}from'./data/units';
import{visibleRecords,visibleContacts,visibleUnits,searchEvents,chapterAt,nextRecordTime}from'./engine';
import{chapters,views,kinds,t,iso,formatDate,formatTime,timeLabel,type View,type Chapter,type Kind,type VisibleEvent}from'./model';
import './style.css';
const defaultTime=t(iso('1942-05-07 08:45'));
function readState(){const p=new URLSearchParams(location.search);const parsed=p.get('time')?Date.parse(p.get('time')!):defaultTime;const now=Number.isFinite(parsed)?Math.max(t(chapters[0].start),Math.min(t(chapters[2].end),parsed)):defaultTime;return{now,view:(['god','us','jp'].includes(p.get('view')??'')?p.get('view'):'god') as View,event:p.get('event')??undefined};}
const initial=readState();
function Icon({name}:{name:string}){return <span aria-hidden="true" className={`icon icon-${name}`}>{({play:'▶',pause:'Ⅱ',back:'‹',next:'›',close:'×',plus:'＋',minus:'−',target:'⌖',search:'⌕',layers:'▱',share:'↗',arrow:'→',compass:'✧',menu:'☰',book:'▤',ship:'♧'}as Record<string,string>)[name]??name}</span>}
function App(){
 const [now,setNow]=useState(initial.now),[view,setView]=useState<View>(initial.view),[selectedId,setSelectedId]=useState(initial.event),[unitId,setUnitId]=useState<string>(),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(30),[guided,setGuided]=useState(false),[query,setQuery]=useState(''),[kind,setKind]=useState<Kind|''>(''),[rail,setRail]=useState(true),[showLayers,setShowLayers]=useState(false),[showResearch,setShowResearch]=useState(false),[toast,setToast]=useState(''),[follow,setFollow]=useState(false),[camera,setCamera]=useState<Camera>({x:0,y:0,k:1}),[zoomTime,setZoomTime]=useState(0),[tab,setTab]=useState<'events'|'fleets'>('events');
 const [layers,setLayers]=useState<Layers>({trails:true,contacts:true,air:true,search:false,bases:true,range:false});
 const chapter=chapterAt(now),chapterInfo=chapters.find(c=>c.id===chapter)!;
 const available=useMemo(()=>visibleRecords(now,view,chapter,view==='god'),[now,view,chapter]);
 const currentEvents=useMemo(()=>available.filter(e=>t(e.at)<=now),[available,now]);
 const selected=available.find(e=>e.id===selectedId&&t(e.at)<=now);
 const unit=visibleUnits(now,view).find(u=>u.id===unitId);
 const dateString=formatDate(now);
 const shown=useMemo(()=>searchEvents(available,query).filter(e=>(!kind||e.kind===kind)&&(chapter!=='battle'||formatDate(e.at)===dateString)),[available,query,kind,chapter,dateString]);
 const reports=visibleContacts(now,view);
 const latest=currentEvents.at(-1);
 const end=t(chapterInfo.end),start=t(chapterInfo.start);
 const timeSpan=chapter==='battle'?(zoomTime===0?86400000:zoomTime===1?21600000:7200000):zoomTime===0?(end-start):zoomTime===1?30*86400000:7*86400000;
 const dayStart=t(iso(new Date(now+36000000).toISOString().slice(0,10)+' 00:00'));
 const rangeBase=chapter==='battle'?dayStart:start;
 const rangeStart=rangeBase+Math.floor((Math.min(now,end-1)-rangeBase)/timeSpan)*timeSpan;
 const rangeEnd=Math.min(end,rangeStart+timeSpan);
 const progress=Math.max(0,Math.min(100,(now-rangeStart)/(rangeEnd-rangeStart)*100));
 const timeEvents=available.filter(e=>t(e.at)>=rangeStart&&t(e.at)<=rangeEnd);
 const timelineGroups=useMemo(()=>{const groups:{pct:number;events:VisibleEvent[]}[]=[];for(const e of timeEvents){const pct=(t(e.at)-rangeStart)/(rangeEnd-rangeStart)*100;const last=groups.at(-1);if(last&&pct-last.pct<1.8)last.events.push(e);else groups.push({pct,events:[e]});}return groups;},[timeEvents,rangeStart,rangeEnd]);
 const [cluster,setCluster]=useState<string[]>([]);
 const lastTick=useRef(0),nowRef=useRef(now);nowRef.current=now;
 const playingRef=useRef(playing);playingRef.current=playing;
 useEffect(()=>{if(!playing)return;lastTick.current=performance.now();const timer=setInterval(()=>{const tick=performance.now(),elapsed=tick-lastTick.current;lastTick.current=tick;const prev=nowRef.current;const delta=chapter==='battle'?speed*60000*elapsed/1000:speed*3600000*elapsed/1000;let next=Math.min(end,prev+delta);if(guided){const candidates=view==='god'?events.filter(e=>e.chapter===chapter&&e.importance).map(e=>t(e.at)):events.filter(e=>e.chapter===chapter&&e.importance).flatMap(e=>e.accounts[view]?.map(a=>t(a.availableAt))??[]);const stop=candidates.filter(time=>time>prev&&time<=next).sort((a,b)=>a-b)[0];if(stop){next=stop;setPlaying(false);const e=visibleRecords(next,view,chapter).filter(e=>e.importance&&t(e.at)===stop).at(-1);setSelectedId(e?.id);setUnitId(undefined);setCluster([]);}}if(next>=end)setPlaying(false);setNow(next);},100);return()=>clearInterval(timer);},[playing,speed,guided,chapter,end,view]);
 useEffect(()=>{const p=new URLSearchParams({time:new Date(now).toISOString(),view});if(selectedId)p.set('event',selectedId);history.replaceState(null,'',`?${p}`);},[Math.floor(now/60000),view,selectedId]);
 useEffect(()=>{function pop(){const s=readState();setNow(s.now);setView(s.view);setSelectedId(s.event);setPlaying(false);}window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer);}},[toast]);
 useEffect(()=>{if(selectedId&&!selected){setSelectedId(undefined);setToast('当前时刻与视角下没有可显示的记录。');}if(unitId&&!unit)setUnitId(undefined);setCluster([]);},[view,now,chapter]);
 function jump(value:number){setNow(Math.max(start,Math.min(end,value)));setPlaying(false);setCluster([]);}
 function chooseChapter(id:Chapter){const c=chapters.find(c=>c.id===id)!;setNow(id==='battle'?t(iso('1942-05-04 07:01')):t(c.start));setPlaying(false);setSelectedId(undefined);setUnitId(undefined);setFollow(false);setCamera({x:0,y:0,k:1});setQuery('');setKind('');setZoomTime(0);}
 function selectEvent(id:string){const e=available.find(e=>e.id===id);if(!e)return;setNow(Math.max(start,t(e.at)));setSelectedId(id);setUnitId(undefined);setPlaying(false);setCluster([]);setFollow(true);}
 function switchView(v:View){setView(v);setFollow(false);setCluster([]);}
 function step(direction:1|-1){const target=nextRecordTime(now,view,chapter,direction);if(target===undefined){setPlaying(false);setToast(direction===1?'本章已无后续记录，可切换章节。':'已到本章最早记录。');return;}const record=visibleRecords(target,view,chapter).filter(e=>t(e.at)===target).at(-1);setNow(target);setSelectedId(record?.id);setUnitId(undefined);setPlaying(false);setCluster([]);setFollow(false);}

 useEffect(()=>{function keyboard(e:KeyboardEvent){if(e.key==='Escape'&&!showResearch){setSelectedId(undefined);setUnitId(undefined);setShowLayers(false);setCluster([]);return;}const el=e.target as HTMLElement;if(el.closest('input,select,textarea,button,[role="button"]')||el.isContentEditable||showResearch)return;if(e.code==='Space'){e.preventDefault();setPlaying(v=>!v);}if(e.key==='ArrowRight'){e.preventDefault();step(1);}if(e.key==='ArrowLeft'){e.preventDefault();step(-1);}if(e.key==='Escape'){setSelectedId(undefined);setUnitId(undefined);setShowLayers(false);}}window.addEventListener('keydown',keyboard);return()=>window.removeEventListener('keydown',keyboard);},[now,available,showResearch]);
 async function share(){try{await navigator.clipboard.writeText(location.href);setToast('当前时间与视角的链接已复制。');}catch{setToast('当前地址已包含时间与视角，可直接复制浏览器地址。');}}
 const focusPoint=follow?(unit?.point??selected?.location):undefined;
 return <main className={`atlas ${rail?'':'rail-closed'}`}>
  <header className="topbar"><a className="brand" href="/" aria-label="珊瑚海首页"><svg viewBox="0 0 40 40"><circle cx="20" cy="20" r="17"/><path d="M20 1 24 20 20 39 16 20ZM1 20H39"/></svg><span>珊瑚海<small>CORAL SEA · 1942</small></span></a>
   <nav className="chapters" aria-label="历史章节">{chapters.map((c,i)=><button className={c.id===chapter?'active':''} onClick={()=>chooseChapter(c.id)} key={c.id}><span>0{i+1}</span>{c.name}</button>)}</nav>
   <div className="top-actions"><button onClick={()=>setShowResearch(true)}><Icon name="book"/>史料与说明</button><button className="square" onClick={share} aria-label="复制当前回放链接"><Icon name="share"/></button></div>
  </header>
  <section className="workspace">
   <SeaMap now={now} view={view} chapter={chapter} events={currentEvents} selected={selected} camera={camera} setCamera={setCamera} onManual={()=>setFollow(false)} onEvent={selectEvent} onContact={id=>{const record=currentEvents.filter(e=>e.eventId===id||e.id===id).at(-1);if(record)selectEvent(record.id);}} onUnit={id=>{setUnitId(id);setSelectedId(undefined);setFollow(false);}} layers={layers} followPoint={focusPoint}/>
   <aside className="event-rail" aria-label="事件目录"><div className="rail-heading"><span className="eyebrow">CHAPTER {chapters.findIndex(c=>c.id===chapter)+1} / 03</span><button className="square" onClick={()=>setRail(false)} aria-label="收起事件目录"><Icon name="back"/></button></div><h1>{chapterInfo.name}</h1><p className="rail-intro">{chapterInfo.intro}</p>
    <div className="rail-tabs"><button className={tab==='events'?'active':''} onClick={()=>setTab('events')}>事件日志</button><button className={tab==='fleets'?'active':''} onClick={()=>setTab('fleets')}>参战部队</button></div>
    {tab==='events'?<><label className="search-box"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索事件、舰船、人物" aria-label="搜索当前可见事件"/>{query&&<button onClick={()=>setQuery('')} aria-label="清除搜索">×</button>}</label>
     <div className="filter-line"><span>{chapter==='battle'?dateString.slice(5):'本章事件'}</span><select aria-label="筛选事件类型" value={kind} onChange={e=>setKind(e.target.value as Kind|'')}><option value="">全部类型</option>{Object.entries(kinds).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></div>
     <div className="event-list">{shown.length?shown.map(e=><button key={e.id} className={`event-row ${e.id===selectedId?'selected':''} ${t(e.at)>now?'future':''}`} onClick={()=>selectEvent(e.id)}><span className={`event-dot side-${e.side}`}/><span className="event-meta">{chapter==='battle'?timeLabel(e):`${formatDate(e.at).slice(5)} · ${timeLabel(e)}`}<small>{kinds[e.kind]}</small></span><strong>{e.title}</strong>{e.importance&&<span className="key-event">关键节点</span>}</button>):<div className="empty-state"><span>⌕</span><p>{query||kind?'没有匹配的可见记录':'此时尚无可显示的记录'}</p><small>推进时间，等待新的事件与报告。</small></div>}</div>
    </>:<div className="unit-list"><p className="muted">{chapter==='battle'?'按当前视角显示的部队':'部队追踪在战役章节开放'}</p>{chapter==='battle'&&visibleUnits(now,view).map(u=><button key={u.id} onClick={()=>{setUnitId(u.id);setSelectedId(undefined);}}><span className={`unit-symbol side-${u.side}`}>{u.side==='us'?'▰':'◆'}</span><strong>{u.name}</strong><small>{u.english}</small><p>{u.state}</p></button>)}</div>}
    <div className="rail-footer"><span className="live-dot"/>历史回放<span>{view==='god'?'史料重建':'按已知信息显示'}</span></div>
   </aside>
   {!rail&&<button className="reopen" onClick={()=>setRail(true)}><Icon name="menu"/>事件目录</button>}
   <div className="map-top"><div className="view-switch" role="group" aria-label="选择观察视角">{(['god','us','jp']as View[]).map(v=><button className={view===v?'active':''} onClick={()=>switchView(v)} key={v}><span className={`view-glyph ${v}`}>{v==='god'?'◉':v==='us'?'▰':'◆'}</span>{views[v]}</button>)}</div><div className="perspective-note">{view==='god'?'双方实际事件与情报 · 史料中的未知仍保留':chapter!=='battle'?'战区指挥层级概括 · 按当时可知信息呈现':view==='us'?'弗莱彻指挥部 · 敌情仅按已收到的报告呈现':'高木／原指挥部 · 敌情仅按已收到的报告呈现'}</div></div>
   <div className="map-stamp"><span className="eyebrow">{chapter==='battle'?'BATTLE OF THE CORAL SEA':'THE PACIFIC THEATER'}</span><h2>{chapter==='battle'?'迷雾中的航母对决':chapterInfo.name}</h2><p>{formatDate(now)}<i/>战区时间 UTC+10</p></div>
   <div className="map-tools"><button className="square" aria-label="放大海图" onClick={()=>setCamera(c=>({...c,k:Math.min(4,c.k*1.25)}))}><Icon name="plus"/></button><button className="square" aria-label="缩小海图" onClick={()=>setCamera(c=>({...c,k:Math.max(.55,c.k/1.25)}))}><Icon name="minus"/></button><hr/><button className="square" aria-label="回到战区" onClick={()=>{setCamera({x:0,y:0,k:1});setFollow(false);}}><Icon name="target"/></button><button className={`square ${showLayers?'active':''}`} aria-label="地图图层" aria-expanded={showLayers} onClick={()=>setShowLayers(v=>!v)}><Icon name="layers"/></button></div>
   {showLayers&&<div className="layer-panel"><strong>海图图层</strong>{Object.entries({trails:'已记录航迹',contacts:'情报接触',air:'航空出击方向',search:'搜索方向（示意）',bases:'基地与地名',range:'200 海里参考圈'}).map(([id,label])=><label key={id}><input type="checkbox" checked={layers[id as keyof Layers]} onChange={e=>setLayers(l=>({...l,[id]:e.target.checked}))}/>{label}</label>)}<small>虚线连接记录位置，搜索扇区与参考圈均为示意。</small></div>}
   <div className="map-bottom"><div className="legend"><span><b className="us">▰</b>盟军部队</span><span><b className="jp">◆</b>日军部队</span><span><b className="intel">◇</b>情报接触</span></div><span className="map-disclaimer">真实海岸线 · 舰位按记录／区域示意 · {follow?'跟随所选对象':'自由探索'}</span></div>
   {!selected&&!unit&&latest&&<button className="current-brief" onClick={()=>selectEvent(latest.id)}><span className="eyebrow">{view==='god'?'LATEST EVENT':'LATEST REPORT'}<i/>{timeLabel(latest)}</span><strong>{latest.title}<Icon name="arrow"/></strong><p>{latest.body.slice(0,67)}{latest.body.length>67?'…':''}</p></button>}
   {(selected||unit)&&<aside className="detail-panel" aria-label={selected?'事件详情':'部队详情'}><div className="detail-top"><span className="eyebrow">{selected?'EVENT RECORD':'TASK FORCE'}</span><button className="square" onClick={()=>{setSelectedId(undefined);setUnitId(undefined);setFollow(false);}} aria-label="关闭详情"><Icon name="close"/></button></div>
    {selected?<><div className="detail-date">{formatDate(selected.at)}<span>{timeLabel(selected)}</span></div><h2>{selected.title}</h2><div className="detail-tags"><span>{kinds[selected.kind]}</span><span>{selected.basis}</span></div><p className="detail-body">{selected.body}</p><div className="detail-place"><Icon name="target"/>{selected.place}</div>
    {selected.rawTime&&<p className="source-clock">{selected.precision==='record'?'原文时标':'来源日期／编排节点'}：{selected.rawTime}{selected.sourceOffset?` · UTC+${selected.sourceOffset}${selected.sourceOffset===11?' → 已减1小时':''}`:' · 原始时区未明；精确跨源排序未定'}</p>}
    {selected.history&&selected.history.length>1&&<div className="detail-section account-history"><h3>报告与修正 · 保留原始记录</h3>{selected.history.map((a,i)=><div key={a.availableAt}><small>{formatTime(a.availableAt)} · {i===0?'最初报告':'后续修正'}</small><strong>{a.title}</strong><p>{a.body}</p><button onClick={()=>{setNow(t(a.availableAt));setSelectedId(i===0?selected.eventId:`${selected.eventId}~${i}`);setPlaying(false);}}>回到这条记录到达时 ↗</button></div>)}</div>}
    {reports.filter(c=>c.eventId===(selected.eventId??selected.id)).map(c=><div className="detail-section" key={c.id}><h3>当时的接触标记</h3><p>{c.body}</p><p className="muted">{c.certainty} · 最后报告点保留至下一次接触／修正；已经过 {c.ageMinutes} 分钟。</p></div>)}
    {selected.units.length>0&&<div className="detail-section"><h3>关联部队</h3>{selected.units.map(id=><button className="linked-unit" key={id} onClick={()=>{setUnitId(id);setSelectedId(undefined);setFollow(true);}}>{units.find(u=>u.id===id)?.name??id}<Icon name="next"/></button>)}</div>}
    {selected.note&&<div className="evidence-note"><span>◷</span><p>{selected.note}</p></div>}
    {view==='god'&&<div className="detail-section"><h3>换一个视角看此刻</h3><div className="compare-buttons"><button onClick={()=>switchView('us')}>美军当时知道什么 <Icon name="arrow"/></button><button onClick={()=>switchView('jp')}>日军当时知道什么 <Icon name="arrow"/></button></div></div>}
    {selected.relation&&<div className="detail-section"><h3>前因与后果</h3>{selected.relation.map(r=><button className="relation" key={r.id} onClick={()=>{const e=events.find(e=>e.id===r.id);if(e){setNow(t(e.at));setSelectedId(e.id);setCamera({x:0,y:0,k:1});setFollow(false);}}}><small>{r.type}</small><strong>{events.find(e=>e.id===r.id)?.title}</strong><p>{r.text}</p></button>)}</div>}
    <div className="detail-section citations"><h3>史料依据</h3>{selected.citations.map((c,i)=><a href={sources[c.source]?.url} key={c.source+i} target="_blank" rel="noreferrer"><span>{String(i+1).padStart(2,'0')}</span><div>{view==='god'?sources[c.source]?.title:'查看该记录的史料'}<small>{view==='god'?c.locator:'外部史料包含事后完整叙述'}</small></div><Icon name="share"/></a>)}</div></>:unit?<><span className={`unit-symbol side-${unit.side}`}>{unit.side==='us'?'▰':'◆'}</span><h2>{unit.name}</h2><p className="eyebrow">{unit.english}</p><div className="unit-status">{unit.state}</div><div className="detail-section"><h3>指挥</h3><p>{unit.commander}</p><h3>编成与任务</h3><p>{unit.composition}</p><p>{unit.task}</p></div><div className="evidence-note"><p>最后位置记录：{formatDate(unit.lastFix)} {unit.positionPrecision==='record'?formatTime(unit.lastFix):'（区域／日期级）'}。{unit.note}。没有后续定位时保留最后位置。</p></div><button className={`primary follow ${follow?'following':''}`} onClick={()=>setFollow(v=>!v)}><Icon name="target"/>{follow?'停止跟随':'跟随此部队'}</button><div className="detail-section"><h3>截至此刻的记录</h3>{currentEvents.filter(e=>e.units.includes(unit.id)).slice(-8).reverse().map(e=><button className="unit-event" key={e.id} onClick={()=>selectEvent(e.id)}><small>{formatDate(e.at).slice(5)} {timeLabel(e)}</small>{e.title}</button>)}</div></>:null}
   </aside>}
   {toast&&<div className="toast" role="status">{toast}</div>}
  </section>
  <footer className="timeline"><div className="timeline-top"><div className="date-control"><span className="eyebrow">{chapter==='battle'?'MAY 1942':'PACIFIC WAR'}</span><label><input type="date" aria-label="选择回放日期" min={new Date(start+36000000).toISOString().slice(0,10)} max={new Date(end+36000000).toISOString().slice(0,10)} value={new Date(now+36000000).toISOString().slice(0,10)} onChange={e=>{if(e.target.value){const date=iso(e.target.value+(chapter==='battle'?' 08:45':' 23:59'));jump(t(date));setSelectedId(undefined);}}}/></label><strong>{formatTime(now)}</strong><small>UTC+10</small></div>
   {chapter==='battle'&&<div className="day-tabs" aria-label="战役日期">{[4,5,6,7,8].map(d=><button key={d} className={new Date(now+36000000).getUTCDate()===d?'active':''} onClick={()=>{setNow(t(iso(`1942-05-0${d} 08:45`)));setSelectedId(undefined);setPlaying(false);}}><span>5 月 {d} 日</span><small>{({4:'图拉吉',5:'会合',6:'搜索',7:'误判',8:'对决'}as Record<number,string>)[d]}</small></button>)}</div>}
   <div className="timeline-options"><label><input type="checkbox" checked={guided} onChange={e=>setGuided(e.target.checked)}/>引导回放</label>{<select aria-label="时间线缩放" value={zoomTime} onChange={e=>setZoomTime(Number(e.target.value))}><option value="0">{chapter==='battle'?'全天':'全章'}</option><option value="1">{chapter==='battle'?'6 小时':'30 天'}</option><option value="2">{chapter==='battle'?'2 小时':'7 天'}</option></select>}</div>
  </div>
  <div className="timeline-bottom"><div className="playback"><button className="square" aria-label="上一个事件" onClick={()=>step(-1)}><Icon name="back"/></button><button className="play-button" onClick={()=>{if(now>=end)setNow(start);setPlaying(v=>!v);}} aria-label={playing?'暂停回放':'开始回放'}><Icon name={playing?'pause':'play'}/></button><button className="square" aria-label="下一个事件" onClick={()=>step(1)}><Icon name="next"/></button><select aria-label="播放速度" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value="5">慢速</option><option value="30">标准</option><option value="120">快速</option></select><small>每秒 {speed} {chapter==='battle'?'分钟':'小时'}</small></div>
   <div className="time-track"><div className="time-ticks">{Array.from({length:7},(_,i)=>{const time=rangeStart+(rangeEnd-rangeStart)*i/6;return<span key={i}>{chapter==='battle'?formatTime(time):formatDate(time).slice(5)}</span>;})}</div><div className="timeline-line"><div className="timeline-fill" style={{width:`${progress}%`}}/>{timelineGroups.map((g,i)=><button key={i} className={`timeline-point ${g.events.some(e=>e.importance)?'important':''} ${g.events.every(e=>t(e.at)>now)?'future':''}`} style={{left:`${g.pct}%`}} aria-label={g.events.length>1?`${g.events.length} 条可见事件，展开选择`:g.events[0].title} title={g.events.map(e=>e.title).join(' / ')} onClick={()=>g.events.length===1?selectEvent(g.events[0].id):setCluster(g.events.map(e=>e.id))}>{g.events.length>1?g.events.length:''}</button>)}<div className="time-cursor" style={{left:`${progress}%`}}><span>{formatTime(now)}</span></div></div><input className="timeline-slider" type="range" aria-label="拖动回放时间" min={0} max={Math.round((rangeEnd-rangeStart)/60000)} step={1} value={Math.round((now-rangeStart)/60000)} aria-valuetext={`${formatDate(now)} ${formatTime(now)} UTC+10`} onChange={e=>jump(rangeStart+Number(e.target.value)*60000)}/><div className="timeline-caption"><span>{view==='god'?'探索完整事件，拖动时间重建当时态势':'仅显示当时已知记录 · 推进时间以接收新情报'}</span><span>{guided?'关键节点自动暂停':'空格播放 / 暂停 · ← → 跳转'}</span></div>
    {cluster.length>0&&<div className="cluster-popup"><button className="cluster-close" onClick={()=>setCluster([])} aria-label="关闭事件选择">×</button>{cluster.map(id=>available.find(e=>e.id===id)).filter(Boolean).map(e=><button key={e!.id} onClick={()=>selectEvent(e!.id)}><small>{timeLabel(e!)}</small>{e!.title}</button>)}</div>}
   </div>
  </div></footer>
  {showResearch&&<Research onClose={()=>setShowResearch(false)} view={view}/>}
  <div className="mobile-message"><span>✧</span><h1>在大屏幕上展开这场海战</h1><p>本海图为桌面浏览设计。请使用宽度至少 1100 像素的电脑窗口，探索时间线、舰队与情报。</p></div>
 </main>;
}
function Research({onClose,view}:{onClose:()=>void;view:View}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.focus();function handler(e:KeyboardEvent){if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=ref.current?.querySelectorAll<HTMLElement>('button,a,[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}window.addEventListener('keydown',handler);return()=>{window.removeEventListener('keydown',handler);previous?.focus();};},[onClose]);return <div className="modal-backdrop" onClick={onClose}><div className="research-modal" role="dialog" aria-modal="true" aria-labelledby="research-title" tabIndex={-1} ref={ref} onClick={e=>e.stopPropagation()}><button className="modal-close square" onClick={onClose} aria-label="关闭史料说明">×</button><span className="eyebrow">READING THE RECORD</span><h2 id="research-title">这张海图如何重建历史</h2><p className="research-lead">事实、当时的报告，以及今天的解释，是三种不同的记录。</p><div className="research-grid"><section><h3>时间并不总是精确</h3><p>界面统一按 UTC+10 编排；「约」表示范围或估计，「当日」表示只确定日期，节点放在当日结束。ONI在5月7日17:00调整舰钟至UTC+11，此后原文时刻减一小时显示。其他来源时间体系未明时保留约时，不据此断言跨来源的分钟先后。</p></section><section><h3>地图保留未知</h3><p>海岸线来自 Natural Earth。舰位来自记录坐标或明确标注的区域示意，虚线连接已有位置。搜索扇区、参考圈和飞行方向用于解释，均非完整实测航迹。</p></section><section><h3>阵营不是实时全知</h3><p>美军以弗莱彻指挥部、日军以高木／原指挥部为中心。接收时刻缺失时保守解锁；只能确定阵营已知的事件标为「阵营层面重建」。背景与后续使用战区层级概括。</p></section><section><h3>如何处理史料矛盾</h3><p>战时识别和战果可能错误。保留报告与修正，关键时刻说明版本差异。已对读日方参战参谋的USSBS战后讯问与美军战时叙述。回忆中的错误不直接当作事实；《战史丛书》第49卷正文尚未全面对读，日方接收分钟仍有缺口。</p></section></div><h3>来源目录</h3>{view!=='god'&&<p className="evidence-note">以下是完整研究目录。外部史料包含事后叙述与战果，可能超出当前阵营当时掌握的信息。</p>}<div className="source-list">{Object.entries(sources).map(([id,s],i)=><a href={s.url} target="_blank" rel="noreferrer" key={id}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{view==='god'?s.title:`研究资料 ${String(i+1).padStart(2,'0')}`}</strong><small>{s.author} · {s.year}</small>{view==='god'&&<p>{s.note}</p>}</div><Icon name="share"/></a>)}</div><p className="research-foot">资料检索：2026-09-12 · 中文为整理转述 · <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth 公有领域地图数据</a></p></div></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
